[workspace]
# Try
# require version 2 to avoid "feature" additiveness for dev-dependencies
# https://doc.rust-lang.org/cargo/reference/resolver.html#feature-resolver-version-2
resolver = "2"

members = [
    "backend-comparison",
    "crates/*",
    "crates/burn-import/pytorch-tests",
    "crates/burn-import/onnx-tests",
    "examples/*",
    "examples/pytorch-import/model",
    "xtask",
]

exclude = ["examples/notebook"]

[workspace.package]
edition = "2021"
version = "0.13.1"
readme = "README.md"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
async-trait = "0.1.79"
bytemuck = "1.14"
candle-core = { version = "0.4.1" }
clap = { version = "4.5.4", features = ["derive"] }
colored = "2.1.0"
console_error_panic_hook = "0.1.7"
csv = "1.3.0"
dashmap = "5.5.3"
dirs = "5.0.1"
fake = "2.9.1"
flate2 = "1.0.28"
float-cmp = "0.9.0"
getrandom = { version = "0.2.13", default-features = false }
gix-tempfile = { version = "11.0.0", features = ["signals"] }
globwalk = "0.9.1"
hashbrown = "0.14.2"
indicatif = "0.17.8"
js-sys = "0.3.69"
libm = "0.2.8"
log = { default-features = false, version = "0.4.21" }
pretty_assertions = "1.4"
proc-macro2 = "1.0.79"
protobuf = "3.3"
protobuf-codegen = "3.3"
quote = "1.0.33"
percent-encoding = "2.3.1"
r2d2 = "0.8.10"
r2d2_sqlite = { version = "0.25.0" }
rayon = "1.10.0"
regex = "1.10.4"
reqwest = "0.11.27"
rmp-serde = "1.1.2"
rstest = "0.18.2"
rusqlite = { version = "0.32.0" }
rust-format = { version = "0.3.4" }
sanitize-filename = "0.5.0"
serde_rusqlite = "0.36.0"
serde-wasm-bindgen = "0.6.5"
spin = { version = "0.9.8", features = ["mutex", "spin_mutex"] }
strum = "0.25.0"
strum_macros = "0.25.3"
syn = { version = "2.0", features = ["full", "extra-traits"] }
tempfile = "3.10.1"
thiserror = "1.0.58"
tokio = { version = "1.37.0", features = ["rt", "macros"] }
tracing-appender = "0.2.3"
tracing-core = "0.1.32"
tracing-subscriber = "0.3.18"
wasm-bindgen = "0.2.88"
wasm-bindgen-futures = "0.4.42"
wasm-logger = "0.2.0"
wasm-timer = "0.2.5"
md5 = "0.7.0"
serial_test = "3.0.0"
web-time = "1.1.0"
hound = "3.5.1"
image = "0.24.9"
zip = "0.6.6"

# Terminal UI
ratatui = "0.25"
crossterm = "0.27"

# WGPU stuff
futures-intrusive = "0.5"
text_placeholder = "0.5.0"
pollster = "0.3"
wgpu = "0.19.4"

# Benchmarks and Burnbench
arboard = "3.3.2"
github-device-flow = "0.2.0"
os_info = "3.8.2"
wsl = "0.1.0"

bincode = { version = "2.0.0-rc.3", features = [
    "alloc",
    "serde",
], default-features = false }

#
# The following packages disable the "std" feature for no_std compatibility
#
derive-new = { version = "0.6.0", default-features = false }

half = { version = "2.4.1", features = [
    "alloc",
    "num-traits",
    "serde",
], default-features = false }
ndarray = { version = "0.15.6", default-features = false }
matrixmultiply = { version = "0.3.8", default-features = false }
openblas-src = "0.10.9"
blas-src = { version = "0.9.0", default-features = false }
num-traits = { version = "0.2.18", default-features = false, features = [
    "libm",
] } # libm is for no_std
rand = { version = "0.8.5", default-features = false, features = [
    "std_rng",
] } # std_rng is for no_std
rand_distr = { version = "0.4.3", default-features = false }
serde = { version = "1.0.197", default-features = false, features = [
    "derive",
    "alloc",
] } # alloc is for no_std, derive is needed
serde_json = { version = "1.0.115", default-features = false }
uuid = { version = "1.8.0", default-features = false }

libc = "0.2.153"
tch = "0.15.0"
nvml-wrapper = "0.9.0"
sysinfo = "0.30.8"
systemstat = "0.2.3"


[profile.dev]
debug = 0 # Speed up compilation time and not necessary.
